// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-LLM0OrcRv08WaJUCj3ZwTQ_Q0wFVbc',
    appId: '1:524581950994:web:ef412068ad910ce8d12acb',
    messagingSenderId: '524581950994',
    projectId: 'ibuild-construir-e-reformar',
    authDomain: 'ibuild-construir-e-reformar.firebaseapp.com',
    databaseURL: 'https://ibuild-construir-e-reformar.firebaseio.com',
    storageBucket: 'ibuild-construir-e-reformar.appspot.com',
    measurementId: 'G-2YXGQH1CYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFnWQrGrug6NWypCl3zjL4zURwUeLDFiw',
    appId: '1:524581950994:android:32309805ef6406e6d12acb',
    messagingSenderId: '524581950994',
    projectId: 'ibuild-construir-e-reformar',
    databaseURL: 'https://ibuild-construir-e-reformar.firebaseio.com',
    storageBucket: 'ibuild-construir-e-reformar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl18mpUxEwKRao7gxRkPeHezDw_MjmCPA',
    appId: '1:524581950994:ios:62ced5d014fee2b0d12acb',
    messagingSenderId: '524581950994',
    projectId: 'ibuild-construir-e-reformar',
    databaseURL: 'https://ibuild-construir-e-reformar.firebaseio.com',
    storageBucket: 'ibuild-construir-e-reformar.appspot.com',
    androidClientId: '524581950994-0fsi8trn71qdh1gh72atu5suoo5q1iak.apps.googleusercontent.com',
    iosClientId: '524581950994-imitdtdb31j09p3jmivp54rmrdors6u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibuildDash',
  );
}
